### ISSUE TITLE
Create multi-version support

### ISSUE THREAD

**Issue by laptoppunk** [CCr4ft3r/actions-of-stamina#29]
AOS 0.5.0 seems to only be compatible with the newest create version, 0.5.1. I'm stuck using 0.5.0 due to mod conflicts and was wondering / hoping it was possible that AOS could support older create versions

**Comment by CCr4ft3r** [comment]
Sorry, but I will not do that. Let me explain the reason:

The dilemma that AoS is facing is that most mods doesn't provide a stable API for this usecase. 
And to be honest: Why should they? It would be definitely better if each mod implements Feathers compatibility by itself.

Therefore AoS has to inject its own code into other mods to consume stamina and prevent actions.
That itself is not the problem - many mods are doing this with Forge and Minecraft code. But these are just two dependencies, that don't change that frequently. AoS supports many more mods that could update anytime.
Supporting multiple versions of many other mods would lead into some kind of mess.
That's why I will only support the latest version of supported mods that were available on the implementation time of the latest update.

Even though I still like the mod idea it's kind of problematic in terms of maintenance and stability, since every supported mod can break with the next update.
